### ISSUE TITLE
Peg spaCy model to specific release on request

### ISSUE THREAD

**Issue by kamwoods** [libratom/libratom#116]
Method to request specific model release; https://github.com/explosion/spacy-models/releases

e.g. specify version during invocation:

Pulls current model:
(venv) user@host:~$ ratom entities --spacy-model xx_ent_wiki_sm /path/to/PST-or-mbox-file-or-directory

Pulls specific existing model:
(venv) user@host:~$ ratom entities -pv --spacy-model xx_ent_wiki_sm-2.2.5 /path/to/PST-or-mbox-file-or-directory

**Comment by adetorcy** [comment]
Addressed by #119
