### ISSUE TITLE
Is this not able to write emls that have attachments?

### ISSUE THREAD

**Issue by afminmax** [libratom/libratom#144]
Hi, 
Interesting bit of code here. I'm interested in testing it for some ML analysis but need a clarification. 
The following bit in the readme states:

_The -m flag can be added to this command to write message bodies (stripped of inline attachments and markup) and message headers to the message table:_

Does this mean that eml with mime attachments cannot be written into the pst?

Thanks.

**Comment by adetorcy** [comment]
By default `ratom entities` or `ratom report` don't include message bodies in their database output, to save space. `message.body` will be null.

With `-m` you will have message bodies in the DB, but stripped of markup and inline attachments (e.g. base64, uuencoded).

**Comment by afminmax** [comment]
Hi thanks for the quick clarification! I'll have to pass on this as I'm moving EML's into and out of PST's at a fair clip and they need their data preserved. Much appreciated.
