### ISSUE TITLE
Installation links on pypi are not quite correct

### ISSUE THREAD

**Issue by thadguidry** [libratom/libratom#152]
On the [README.md](https://github.com/libratom/libratom/blob/master/README.md) here in the repo the links have the trailing header correctly:

`https://github.com/libratom/libratom#windows-environment-setup`

However, on PyPi.org for some reason, there is a slash character being added before the header and should not be and makes the links ineffective on PyPi to quickly navigate to those sections.

`https://github.com/libratom/libratom/#windows-environment-setup`

> Need guidance setting up an environment on your platform? Navigate to one of the linked sections below before continuing.
>
>  *  [Windows environment setup](https://pypi.org/project/libratom/#windows-environment-setup)
>  *  [macOS environment setup](https://pypi.org/project/libratom/#macos-environment-setup)
>  *  [Ubuntu environment setup](https://pypi.org/project/libratom/#ubuntu-environment-setup)

Perhaps someone who is responsible for the PyPi publishing can fix this easily?

**Comment by adetorcy** [comment]
Thank you for reporting this. It looks like there is an open issue for this in the code that PyPI uses to generate the project page:
https://github.com/pypa/readme_renderer/issues/163

I would rather keep relative links our README page for maintainability and not take any action for now.
