### ISSUE TITLE
About get subject byte array

### ISSUE THREAD

**Issue by spchenjie** [libratom/libratom#186]
Could team create an api to return subject byte array?
I don't know why always return  the subject string by utf-8.

**Comment by adetorcy** [comment]
Use `str.encode()` or `bytearray()` if you want bytes

**Comment by spchenjie** [comment]
Thanks for your answer.

But we got the problem about the encode function.
Now we use the lib to analyze the email which encoding by japanese language code.
For the subject,
1, we encode the subject by utf-8 to the bytearray
2, we detected the content language code
3, we use the detected code to decode the subject bytearray

We find that fifty percent email subject could not be displayed correctly.
We think the problem is that first time subject decode by utf-8
Some word has been changed so it could not be encode to what it is.

So if you can add subject return value by byte array like email content, I think the problem could be fix.

**Comment by adetorcy** [comment]
I see. There might be better approaches but you can try to do something like this:

```python3
from typing import Optional
import pypff

# https://github.com/libyal/libpff/blob/20211114/libpff/libpff_mapi.h#L212
LIBPFF_ENTRY_TYPE_MESSAGE_SUBJECT = int("0x0037", base=16)

def get_message_subject_bytes(msg: pypff.message) -> Optional[bytes]:
    # As far as I can tell a message object has one record set (?)
    record = msg.record_sets[0]
    
    # Find the subject entry and return its raw data
    for entry in record.entries:
        if entry.entry_type == LIBPFF_ENTRY_TYPE_MESSAGE_SUBJECT:
            return entry.data
```
