### ISSUE TITLE
need to extract eml with message header, content, attachment

### ISSUE THREAD

**Issue by nandasba** [libratom/libratom#190]
we are struggling to extract eml process from pst. I' ding below steps to extract, i need process to extract
1. ratom report example.pst
2. export all pff_identifier from sqlite3
3. create json file with , filename, sha256 value & id_pst(export from sqlite3).
4. ratom emldump file.json file.
i got only message header, without content & attachment  we cannot use that eml which only having header.

kindly advice the process to extract all

**Comment by nandasba** [comment]
We are still facing this issue and awaiting for your response on the stated issue.

**Comment by adetorcy** [comment]
Hello, thanks for reporting this. We will try to address this issue in the next release.

**Comment by nandasba** [comment]
Could you please confirm that when we can expect the next release to fulfill our requirement?
else
Is there any other tool to  fulfill our requirement?

**Comment by adetorcy** [comment]
We cannot confirm if/when your issue will be resolved, but you can try [pffexport](https://manpages.ubuntu.com/manpages/xenial/man1/pffexport.1.html)
